### ISSUE TITLE
Training Code

### ISSUE THREAD

**Issue by jiandandan001** [House-Leo/RealSR-CCL#1]
Thank you for this great work and thank you for sharing the code.

Could you please share the training code of this work? Thanks.

**Comment by House-Leo** [comment]
Hi, @jiandandan001 !

Thanks for your attention! 

Unfortunately, I can not connect to the GPU server now since I have graduated from Guangdong University of Technology. 

I'm focusing on my next topic now, so I have no plans to release training codes in the near future. Please stay tuned :).
